# -*- coding: utf-8 -*-
"""Air quality Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vUTg8V82XTA34hKAYb_MR8xeQFGLCycR
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

df = pd.read_csv("city_day.csv")

df.tail()

# Convert date column
df['Date'] = pd.to_datetime(df['Date'])

# Extract year and month
df['year'] = df['Date'].dt.year
df['month'] = df['Date'].dt.month

# Replace null values with column mean
df.fillna(df.mean(numeric_only=True), inplace=True)

"""Yearly Average AQI Trend"""

yearly_aqi = df.groupby("year")['AQI'].mean()

plt.figure(figsize=(10,5))
plt.plot(yearly_aqi.index, yearly_aqi.values, marker='o')
plt.xlabel("Year")
plt.ylabel("Average AQI")
plt.title("Yearly AQI Trend in India")
plt.grid(True)
plt.show()

"""Top 10 Most Polluted Cities (PM2.5)"""

city_pm = df.groupby("City")['PM2.5'].mean().sort_values(ascending=False).head(10)

plt.figure(figsize=(10,5))
city_pm.plot(kind='bar', color='maroon')
plt.ylabel("Average PM2.5")
plt.title("Top 10 Most Polluted Cities (PM2.5) in India")
plt.xticks(rotation=45)
plt.show()

"""Seasonal Variation of PM2.5"""

season_map = {12:"Winter",1:"Winter",2:"Winter",
              3:"Summer",4:"Summer",5:"Summer",
              6:"Monsoon",7:"Monsoon",8:"Monsoon",
              9:"Post-Monsoon",10:"Post-Monsoon",11:"Post-Monsoon"}

df['season'] = df['month'].map(season_map)

season_pm = df.groupby("season")['PM2.5'].mean()

plt.figure(figsize=(10,5))
season_pm.plot(kind='bar', color='orange')
plt.title("Seasonal Variation of PM2.5 in India")
plt.ylabel("Average PM2.5")
plt.xticks(rotation=0)
plt.show()

"""Pollutant Correlation Heatmap"""

plt.figure(figsize=(9,6))
numeric_cols = ['PM2.5','PM10','NO','NO2','NOx','CO','SO2','O3','NH3','AQI']
corr = df[numeric_cols].corr()

sns.heatmap(corr, annot=False, cmap="coolwarm")
plt.title("Correlation Between Air Pollutants in India")
plt.show()

"""AQI Category Distribution"""

plt.figure(figsize=(7,7))
df['AQI_Bucket'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title("Distribution of AQI Categories in India")
plt.ylabel("")
plt.show()

"""City-wise CO Levels"""

city_co = df.groupby("City")['CO'].mean().sort_values(ascending=False).head(10)

plt.figure(figsize=(10,5))
city_co.plot(kind='bar', color='green')
plt.title("Top 10 Indian Cities by CO Levels")
plt.ylabel("Average CO")
plt.xticks(rotation=45)
plt.show()

"""Scatter Plot (PM2.5 vs AQI)"""

plt.figure(figsize=(8,5))
plt.scatter(df['PM2.5'], df['AQI'], alpha=0.3)
plt.xlabel("PM2.5")
plt.ylabel("AQI")
plt.title("Relationship Between PM2.5 and AQI in India")
plt.grid(True)
plt.show()

print("""
CONCLUSION FOR AIR QUALITY IN INDIA (Using Rohan Rao Dataset)

1. Yearly AQI trends reveal increasing pollution around 2015–2019,
   with slight improvement after 2020 (likely due to lockdown effects).

2. PM2.5 analysis shows that Delhi, Kanpur, Lucknow, and Patna
   are consistently the most polluted cities in India.

3. Seasonal analysis confirms:
   • Winter experiences the HIGHEST pollution
   • Monsoon shows the CLEANEST air

4. Correlation heatmap shows strong relationships between:
   • PM2.5 ↔ PM10
   • NO ↔ NO₂ ↔ NOx
   These indicate vehicle and industrial emission dominance.

5. AQI Category Distribution shows a large portion of days fall
   under "Poor" and "Very Poor," indicating serious health risks.

6. CO analysis highlights metro cities having the highest CO levels
   due to traffic congestion and fuel burning.

7. PM2.5 vs AQI scatter plot shows a strong upward trend —
   meaning PM2.5 is the major contributor to unhealthy AQI.

Overall Conclusion:
Indian cities face severe pollution, especially due to PM2.5 and vehicle emissions.
Major metro and industrial cities show extremely poor air quality,
indicating the need for stronger regulations, cleaner fuels,
and sustainable urban planning.
""")