# -*- coding: utf-8 -*-
"""EDA_on_iris_ds.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OYrX-cf9wUySsDWxXxfS-pavLtLWE6KO
"""

# Import libraries
import pandas as pd
import matplotlib.pyplot as plt

# Load inbuilt dataset from sklearn
from sklearn.datasets import load_iris

# Load dataset
iris = load_iris()

# Convert to DataFrame
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

# Add target column (species)
df['species'] = iris.target

# Map numeric labels to actual names
df['species'] = df['species'].map({
    0: 'setosa',
    1: 'versicolor',
    2: 'virginica'
})

# Show first 5 rows
print("First 5 rows:")
print(df.head())

# Basic info
print("\nDataset Info:")
print(df.info())

# Statistical summary
print("\nStatistical Summary:")
print(df.describe())

# Group by species and get mean
print("\nMean values per species:")
print(df.groupby('species').mean())

# Visualization 1: Scatter plot
plt.figure()
for species in df['species'].unique():
    subset = df[df['species'] == species]
    plt.scatter(subset['sepal length (cm)'], subset['sepal width (cm)'], label=species)

plt.xlabel("Sepal Length")
plt.ylabel("Sepal Width")
plt.title("Sepal Length vs Width")
plt.legend()
plt.show()

# Visualization 2: Histogram
df.hist(figsize=(10, 8))
plt.suptitle("Feature Distributions")
plt.show()

# Visualization 3: Boxplot
df.boxplot(by='species', figsize=(10, 6))
plt.suptitle("Boxplot of Features by Species")
plt.show()