# -*- coding: utf-8 -*-
"""Iris Species Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hL1wEXZZefNTmUjF5QZyGkk_v9wxBVa2
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# ==========================================
# 1. LOAD & PREPARE DATA
# ==========================================
iris = load_iris()
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['species'] = iris.target
df['species_name'] = df['species'].map({0: 'setosa', 1: 'versicolor', 2: 'virginica'})

print("--- Dataset Information ---")
print(f"Shape: {df.shape}")
print(df.describe())

# ==========================================
# 2. VISUALIZATION (THE ANALYSIS)
# ==========================================
# Set aesthetic style
sns.set_theme(style="whitegrid")

# Create a figure with multiple subplots
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Subplot 1: Scatter Plot (Relationship between Petal Length & Width)
sns.scatterplot(ax=axes[0], x='petal length (cm)', y='petal width (cm)',
                hue='species_name', style='species_name', data=df, s=100)
axes[0].set_title('Petal Dimensions by Species')

# Subplot 2: Violin Plot (Distribution of Features)
melted_df = pd.melt(df.drop('species', axis=1), id_vars='species_name',
                    var_name='feature', value_name='value')
sns.violinplot(ax=axes[1], x='feature', y='value', hue='species_name',
               data=melted_df, inner='quartile')
axes[1].set_title('Feature Distribution Density')
plt.xticks(rotation=15)

plt.tight_layout()
plt.show()

# ==========================================
# 3. MACHINE LEARNING (THE PREDICTION)
# ==========================================
# Features and Target
X = iris.data
y = iris.target

# Split data (80% Training, 20% Testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and Train Random Forest
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Make Predictions
y_pred = model.predict(X_test)

# ==========================================
# 4. RESULTS & EVALUATION
# ==========================================
print("\n--- Model Performance ---")
print(f"Accuracy Score: {accuracy_score(y_test, y_pred) * 100:.2f}%")
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))

# Confusion Matrix Visualization
plt.figure(figsize=(6, 4))
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Greens',
            xticklabels=iris.target_names, yticklabels=iris.target_names)
plt.title('Confusion Matrix')
plt.ylabel('Actual Species')
plt.xlabel('Predicted Species')
plt.show()

# Feature Importance - Which feature drove the decision?
importances = model.feature_importances_
feature_names = iris.feature_names
feature_importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': importances})
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

print("\n--- Feature Importance ---")
print(feature_importance_df)