# -*- coding: utf-8 -*-
"""Student_performance_insights.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NXRUCey9kxJveYbXJeIG1Wtg7UqHofS0
"""

"""
Problem Statement:
Educational institutions often collect large amounts of student data, including
scores, attendance, and study hours. However, this data is rarely analyzed
systematically to uncover patterns that could improve student outcomes.

This project aims to analyze student performance data to:
1. Understand relationships between study hours, attendance, and scores
2. Identify high-performing vs low-performing students
3. Visualize trends for better decision-making

We will use Python libraries such as pandas and matplotlib.
"""

import pandas as pd
import matplotlib.pyplot as plt

# Sample dataset creation
# In real projects, this would come from a CSV file

data = {
    'Student': ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
    'StudyHours': [2, 4, 1, 5, 3, 6, 2],
    'Attendance': [75, 85, 60, 90, 80, 95, 70],
    'Score': [50, 65, 40, 80, 70, 85, 55]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display dataset
print("Dataset:\n", df)

# Basic statistics
print("\nStatistical Summary:\n", df.describe())

# Correlation analysis
correlation = df.corr(numeric_only=True)
print("\nCorrelation Matrix:\n", correlation)

# Visualization: Study Hours vs Score
plt.figure()
plt.scatter(df['StudyHours'], df['Score'])
plt.xlabel('Study Hours')
plt.ylabel('Score')
plt.title('Study Hours vs Score')
plt.show()

# Visualization: Attendance vs Score
plt.figure()
plt.scatter(df['Attendance'], df['Score'])
plt.xlabel('Attendance (%)')
plt.ylabel('Score')
plt.title('Attendance vs Score')
plt.show()

# Identify top performers
top_students = df[df['Score'] > 75]
print("\nTop Performing Students:\n", top_students)

# Identify students needing improvement
low_students = df[df['Score'] < 50]
print("\nStudents Needing Improvement:\n", low_students)

# Insights
print("\nInsights:")
print("- Higher study hours generally lead to better scores.")
print("- Attendance also shows a positive relationship with performance.")
print("- Students with low study hours and attendance need support.")