# -*- coding: utf-8 -*-
"""Wine_quality_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OpxFp-jGeAjRza4A-otL8QRG1wuigvwG
"""

# Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load dataset
wine = load_wine()

# Convert to DataFrame
df = pd.DataFrame(wine.data, columns=wine.feature_names)
df['target'] = wine.target

# Show data
print(df.head())

# Info
print("\nDataset Info:")
print(df.info())

# Summary
print("\nSummary Statistics:")
print(df.describe())

# -------------------------------
# 📊 Visualization
# -------------------------------

# Correlation Heatmap
plt.figure()
sns.heatmap(df.corr(), annot=False)
plt.title("Correlation Heatmap")
plt.show()

# Distribution Plot
plt.figure()
sns.histplot(df['alcohol'], kde=True)
plt.title("Alcohol Distribution")
plt.show()

# -------------------------------
# 📉 Data Preparation
# -------------------------------

X = df.drop('target', axis=1)
y = df['target']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# -------------------------------
# 🤖 Model Training
# -------------------------------

model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# -------------------------------
# 📊 Evaluation
# -------------------------------

print("\nAccuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# -------------------------------
# 📈 Confusion Matrix Visualization
# -------------------------------

plt.figure()
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()